#!/bin/bash

echo "🚀 Setup para Deploy em Produção"
echo "================================="

echo ""
echo "📋 CHECKLIST PARA DEPLOY:"
echo ""

echo "✅ 1. BACKEND (Railway):"
echo "   • Acesse: https://railway.app"
echo "   • Conecte seu repositório GitHub"
echo "   • Adicione PostgreSQL database"
echo "   • Configure as variáveis de ambiente:"
echo "     - DATABASE_URL (auto-gerada pelo Railway)"
echo "     - JWT_SECRET (gere uma chave forte)"
echo "     - NODE_ENV=production"
echo "     - CORS_ORIGINS=https://seu-frontend.vercel.app"
echo ""

echo "✅ 2. FRONTEND (Vercel):"
echo "   • Acesse: https://vercel.com"
echo "   • Conecte seu repositório GitHub"
echo "   • Configure Root Directory: frontend"
echo "   • Build Command: npm run build"
echo "   • Output Directory: dist"
echo "   • Configure variável de ambiente:"
echo "     - VITE_API_URL=https://sua-api-railway.up.railway.app"
echo ""

echo "✅ 3. VARIÁVEIS DE AMBIENTE OBRIGATÓRIAS:"
echo ""
echo "BACKEND (Railway):"
echo "DATABASE_URL=postgresql://..."
echo "JWT_SECRET=sua-chave-jwt-super-secreta"
echo "NODE_ENV=production"
echo "CORS_ORIGINS=https://seu-frontend.vercel.app"
echo ""
echo "FRONTEND (Vercel):"
echo "VITE_API_URL=https://sua-api-railway.up.railway.app"
echo ""

echo "🔧 4. COMANDOS ÚTEIS:"
echo ""
echo "# Testar build local:"
echo "npm run build"
echo ""
echo "# Executar em modo produção:"
echo "npm run start:prod"
echo ""
echo "# Verificar variáveis de ambiente:"
echo "cat .env.production.example"
echo ""

echo "📚 5. LINKS ÚTEIS:"
echo "• Railway: https://railway.app"
echo "• Vercel: https://vercel.com"
echo "• Repositório: https://github.com/carl0sfelipe/rentals"
echo ""

echo "🎯 Após o deploy, sua aplicação estará disponível em:"
echo "• Backend: https://sua-api-railway.up.railway.app"
echo "• Frontend: https://seu-projeto.vercel.app"
echo ""

echo "✨ Boa sorte com o deploy!"
